### ISSUE TITLE
Install-OfficeClicktoRun Error

### ISSUE THREAD

**Issue by gknapp63** [OfficeDev/Office-IT-Pro-Deployment-Scripts#186] opened 2016-11-11 14:22 UTC
The above script errors when I run it in our corporate domain with the error "Update Not Running"  We  redirect updating to System Center Config Mgr v1602. I've run the same script on a non domain bound machine the goes direct to microsoft for its updates and it runs and installs Office as expected.

**Comment by johnskydiver** [comment] 2016-11-11 17:40
@gknapp63 I see you are trying to manage office installs with SCCM, which can be tricky.    You haven't given me a lot of info to go off of for this problem.  If the output says "update not running"  have you confirmed that the URL for the office bits on the SCCM server is accessible by the client machine?  have you checked the registry at HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration.  In this regkey path, you should see registry keys for either UpdateURL or CDNBaseUrl.  Can you confirm that the URL for these reg keys is pointing to the update path for the server?  Please let me know.  Thanks.

**Comment by gknapp63** [comment] 2016-11-14 09:12
Maybe I worded the question incorrectly. I'm running the Powershell script "Install-OfficeClicktoRun.ps1 thats part of this repository from an Admin Powershell command window. The script and the configuration xml are located in the same directory. The xml file was generated using the Generate-ODTConfigurationXML.ps1 that's also part of the same repository If I run the script on a domain bound machine I get the Update not Running" error message, If I run the exact same script and configuration.xml from a non domain bound machine 0365Proplus installs as expected. If further information is require please let me know.Thanks

**Comment by johnskydiver** [comment] 2016-11-14 15:27
I see.  One more piece of information might help.  The XML generated on the domain bound client may be different than the XML generated on the non domain bound client, I'm not sure if you just copied the xml over to the non domain bound client, or if you ran the generate xml script on both clients.  If the xml is exactly the same, I would suggest you check your firewall on the domain.  you'll run into issues if the path for the ODT bits are blocked.  Here is a sample of path used to grab the Office bits.  "http://officecdn.microsoft.com/pr/cbc7891e-9126-44de-8a56-2bd6d2e06c48".  Please make sure that URL isn't blocked.  Please let me know if this helps.

**Comment by gknapp63** [comment] 2016-11-15 16:41
Your suspicions are correct its all pointing to our corporate firewalls not allowing access to the Office CDN. I'm talking to our network team with a hope of getting this sorted. Thanks for all your help.

**Comment by johnskydiver** [comment] 2016-11-15 19:30
Glad to hear it's getting sorted out.  Closing the issue as it seems to be resolved.

**Closed by johnskydiver** 2016-11-15 19:30 UTC
