### ISSUE TITLE
Download-OfficeProPlusChannels failing on v32.cab

### ISSUE THREAD

**Issue by paulwetter** [OfficeDev/Office-IT-Pro-Deployment-Scripts#103] opened 2016-04-28 13:08 UTC
Not sure what is going on, but the script is failing and timing out when it get to downloading the v32.cab to find the version information.
Error: `: Exception calling "GetResponse" with "0" argument(s): "The operation has timed out
`

I put together my own workaround by replacing the 'downloadfile' function with the built in 'Start-BitsTransfer' command in PowerShell.  Was a perfect drop in replacement, just had to change the function and parameter names but used the same variables.  Not sure if it works with the error handling or not but, got me downloading again.

For example, replace:
`DownloadFile -url $XMLDownloadURL -targetFile $XMLFilePath`
With
`Start-BitsTransfer -Source $XMLDownloadURL -Destination $XMLFilePath`

Then, delete the entire Function downloadfile block:
`function DownloadFile($url, $targetFile) {...}`

Why not make 'Start-BitsTransfer' the default for the file download?  Yes you have to have BITS enabled, but I don't know that anyone disables it.

**Comment by davguent** [comment] 2016-08-26 12:45
Paul, I know there was a regression in ODT tool where v32.cab was not downloaded as expected which has been fixed in current build 16.0.7213.5776.  I validated this is correct on GitHub repository.  Can you confirm v32.cab downloads as expected?

**Comment by AStigall** [comment] 2016-10-04 19:27
Updates to the ODT appear to have fixed the issue. Please let us know if this is still an issue @paulwetter

**Comment by AStigall** [comment] 2016-10-07 18:31
@paulwetter  It looks like recent changes to the ODT have fixed the issue. Let us know if this is still an issue on your end.

**Comment by BGleasonGH** [comment] 2016-11-10 01:57
I am seeing this issue as well, not sure what is causing it...

PS C:\WINDOWS\system32> Download-OfficeProPlusChannels -TargetDirectory C:\users\<USERNAME>\Desktop\2016 -Channels Current -Bitness v32 -NumVersionsToKeep 6 -Languages en-us -UseChannelFolderShortName $false

Downloading Bitness : 32-Bit
	Downloading Channel: Current
Where-Object : The 'Ieq' operator failed: Exception calling "GetResponse" with "0" argument(s): "The operation has timed out".At 
C:\Users\<USERNAME>\Desktop\Download-OfficeProPlusChannels.ps1:264 char:55
+ ...            $CurrentVersionXML.UpdateFiles.File | ? language -eq "0" |
+                                                      ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (File:PSObject) [Where-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : OperatorFailed,Microsoft.PowerShell.Commands.WhereObjectCommand
 
Where-Object : The 'Ieq' operator failed: Exception calling "GetResponse" with "0" argument(s): "The operation has timed out".At 
C:\Users\<USERNAME>\Desktop\Download-OfficeProPlusChannels.ps1:264 char:55
+ ...            $CurrentVersionXML.UpdateFiles.File | ? language -eq "0" |
+                                                      ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (File:PSObject) [Where-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : OperatorFailed,Microsoft.PowerShell.Commands.WhereObjectCommand
 
Where-Object : The 'Ieq' operator failed: Exception calling "GetResponse" with "0" argument(s): "The operation has timed out".At 
C:\Users\<USERNAME>\Desktop\Download-OfficeProPlusChannels.ps1:284 char:59
+ ...    $CurrentVersionXML.UpdateFiles.File | ? language -eq $languageId |
+                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (File:PSObject) [Where-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : OperatorFailed,Microsoft.PowerShell.Commands.WhereObjectCommand
 
Where-Object : The 'Ieq' operator failed: Exception calling "GetResponse" with "0" argument(s): "The operation has timed out".At 
C:\Users\<USERNAME>\Desktop\Download-OfficeProPlusChannels.ps1:284 char:59
+ ...    $CurrentVersionXML.UpdateFiles.File | ? language -eq $languageId |
+                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (File:PSObject) [Where-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : OperatorFailed,Microsoft.PowerShell.Commands.WhereObjectCommand
 
Where-Object : The 'Ieq' operator failed: Exception calling "GetResponse" with "0" argument(s): "The operation has timed out".At 
C:\Users\<USERNAME>\Desktop\Download-OfficeProPlusChannels.ps1:284 char:59
+ ...    $CurrentVersionXML.UpdateFiles.File | ? language -eq $languageId |
+                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (File:PSObject) [Where-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : OperatorFailed,Microsoft.PowerShell.Commands.WhereObjectCommand

**Comment by BGleasonGH** [comment] 2016-11-10 02:22
Here I am parsing what it is trying to download:

`PS C:\WINDOWS\system32> Download-OfficeProPlusChannels -TargetDirectory C:\users\<USERNAME>\Desktop\2016 -Channels Current -Languages en-us -Bitness v32 -UseChannelFolderShortName $false -NumVersionsToKeep 6

Downloading Bitness : 32-Bit
	Downloading Channel: Current
Downloading http://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/office/data/16.0.7369.2055/Experiment/i320.cab to C:\users\<USERNAME>\Desktop\2016\Current/office/dat
a/16.0.7369.2055/Experiment/i320.cab
Where-Object : The 'Ieq' operator failed: Exception calling "GetResponse" with "0" argument(s): "The operation has timed out".At 
C:\Users\<USERNAME>\Desktop\Download-OfficeProPlusChannels.ps1:264 char:55
+ ...            $CurrentVersionXML.UpdateFiles.File | ? language -eq "0" |
+                                                      ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (File:PSObject) [Where-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : OperatorFailed,Microsoft.PowerShell.Commands.WhereObjectCommand
 
Downloading http://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/office/data/16.0.7369.2055/Experiment/i640.cab to C:\users\<USERNAME>\Desktop\2016\Current/office/dat
a/16.0.7369.2055/Experiment/i640.cab
Where-Object : The 'Ieq' operator failed: Exception calling "GetResponse" with "0" argument(s): "The operation has timed out".At 
C:\Users\<USERNAME>\Desktop\Download-OfficeProPlusChannels.ps1:264 char:55
+ ...            $CurrentVersionXML.UpdateFiles.File | ? language -eq "0" |
+                                                      ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (File:PSObject) [Where-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : OperatorFailed,Microsoft.PowerShell.Commands.WhereObjectCommand
 
Checking for Older Versions
	Channel: Current
		No Versions to Remove

PS C:\WINDOWS\system32> 
PS C:\WINDOWS\system32> Download-OfficeProPlusChannels -TargetDirectory C:\users\<USERNAME>\Desktop\2016 -Channels Current -Languages en-us -Bitness v32 -UseChannelFolderShortName $false -NumVersionsToKeep 6

Downloading Bitness : 32-Bit
	Downloading Channel: Current
Downloading http://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/office/data/16.0.7369.2055/Experiment/i320.cab to C:\users\<USERNAME>\Desktop\2016\Current/office/dat
a/16.0.7369.2055/Experiment/i320.cab
Downloading http://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/office/data/16.0.7369.2055/Experiment/i640.cab to C:\users\<USERNAME>\Desktop\2016\Current/office/dat
a/16.0.7369.2055/Experiment/i640.cab
Checking for Older Versions
	Channel: Current
		No Versions to Remove

PS C:\WINDOWS\system32> `

**Comment by BGleasonGH** [comment] 2016-11-10 02:51
If you change the downloadfile function:

Find this:
`       $responseStream = $response.GetResponseStream()
       $targetStream = New-Object -TypeName System.IO.FileStream -ArgumentList $targetFile, Create
`
Make the below modification:
`       $responseStream = $response.GetResponseStream()
       if(!(Test-Path "$(Split-Path -LiteralPath "$targetFile")")){
         New-Item -ItemType directory -Path "$(Split-Path -LiteralPath "$targetFile")"
       }
       $targetStream = New-Object -TypeName System.IO.FileStream -ArgumentList $targetFile, Create
`

**Comment by johnskydiver** [comment] 2016-11-11 16:07
Issue stems from new sub folder added to downloadable content.  Scripts have been updated, issue is now resolved.

**Closed by johnskydiver** 2016-11-11 16:07 UTC
