### ISSUE TITLE
error with get-officeversion

### ISSUE THREAD

**Issue by jeremy-dr** [OfficeDev/Office-IT-Pro-Deployment-Scripts#175] opened 2016-10-26 02:47 UTC
when i run this to manage local installation - i get the following error get-officeversion parsing C:\\program files\(x86)\\Notepad++ odtconfigurationxml.ps1: 150 charge 26

**Comment by johnskydiver** [comment] 2016-10-27 18:17
@jeremy-dr I've been trying to reproduce this error and have been unable to.  This was an issue we ran into months ago and have since rectified.  I would like a little further detail in order to help figure this out.  Did you pull this script from the "master" branch, and which directory are you using?  Such as Office-ProPlus-Deployment/Deploy-OfficeClickToRun, or Office-ProPlus-Deployment/Generate-ODTConfigurationXML?  Please let me know so I can get this taken care of.  Thanks.

**Comment by jeremy-dr** [comment] 2016-10-27 22:01
it appears to be running into an issue with notepad ++, uninstalling allowed the program to run

**Comment by jeremy-dr** [comment] 2016-10-27 23:47
it appears to be running into an issue with notepad ++, uninstalling allowed the program to run

**Comment by johnskydiver** [comment] 2016-10-28 18:27
Closing thread since you've seem to have resolved the issue

**Closed by johnskydiver** 2016-10-28 18:27 UTC
