### ISSUE TITLE
64-Bits MSI and EXE corrupted

### ISSUE THREAD

**Issue by jpatriarca** [OfficeDev/Office-IT-Pro-Deployment-Scripts#133] opened 2016-07-18 12:09 UTC
When creating MSI and EXE package, based on pre-defined XML file, the generated file are reported as incompatible with 64-Bits Windows 10 with the general message, as described:

This app can't run on your PC
To find a version to your PC, check with the software published

Regarding 32 bits of the generated files, there's no problem with them.
![64bitserror](https://cloud.githubusercontent.com/assets/19894552/16914310/e095f832-4ce8-11e6-8466-12bcbbcbce13.png)

**Comment by johnskydiver** [comment] 2016-07-19 15:08
Hello, I'm currently looking at the issue, and I'm unable to reproduce your error.  Can you please let me know which operating system you're working on, and if possible, let me know the steps you took when this error occurred.  Thanks.

**Comment by jpatriarca** [comment] 2016-07-19 15:24
Hi,

I'm testing the packages using Windows 10 Pro 64 Bits. All the tests we're done on W10.

The MSI gives no feedback about any error. MSIEXEC simply closes without any further notice (i have the no information setting enabled). The EXE gives me the error that i've attached in the last message.

Using the click-to-run with a downloaded source and the XML file the 64 bits package are installed correctly.

I'll try to run some tests in W7 64 bits to give you further information to help you detect and solve the problem.

Thank you

**Comment by johnskydiver** [comment] 2016-07-19 18:33
Could you zip up the exe you created, and post it on this thread, I'd like to try and run it on when of my test machines, also, a copy of the XML you used for import would be nice if it's not too much trouble.

Thanks.

**Comment by jpatriarca** [comment] 2016-07-20 14:23
In the following download, you'll find 3 files: MSI package, EXE package and XML that originated the files. The source is local and not a download, from de Defered Channel. Thanks

https://www.dropbox.com/s/iql5cgff87vcbxo/O36564Bitserror.zip?dl=0

**Comment by johnskydiver** [comment] 2016-07-20 20:06
Thank you for the files, I was able to re-create the error, so I'm going to see if I can rectify it.

**Comment by johnskydiver** [comment] 2016-07-21 15:08
After testing, I discovered that the reason your created files appear to be corrupt is because of the file size.  Since you're embedding the install with 4 different languages, the file size has been increased to over 2 GB.  The created applications from the toolkit are 32 bit apps, with a size limit of 2 GB.  I am currently working on a fix for this, in the mean time, as a work around, you'll want to not select the option for embedding the resource files, if you have a network drive that all your clients have access too, you can use the toolkit to download the resource files on the download tab to the shared drive, and set the Source Path on the products tab under optional at the top to the same network drive.  This will allow the your clients to have the created package install office, and it will retrieve the resource files from that network share.  I hope this helps.  Thanks.

**Comment by jpatriarca** [comment] 2016-07-21 15:45
Thank you for your feedback. Since that the app are 32 bits, it makes sense. My alternative at this time is to do has you're speaking. But since that i have SCCM and multiple locations where the links are weak, fragmentation would be needed and spesific scripts for each source location would be needed, and a lot of time lost. I prefer of a MSI/EXE solution in SCCM for 64 bits Office365 and i'll wait for an app new release to do further testing. Thanks for your help

**Comment by johnskydiver** [comment] 2016-08-16 19:11
Issue has been resolved and is part of the most current toolkit available for download.

**Closed by johnskydiver** 2016-08-16 19:11 UTC
